In [21]:
from src.database import load_gastos, load_param
from src.transform_db import prepare_data
import pandas as pd
import numpy as np

df_raw   = load_gastos()
df_param = load_param()

df = prepare_data(df_raw, df_param)

df

,Data,Local,Valor,Categoria,Pagamento?,Mês Pagamento,Saldo,Mês Pagamento Atual?
0,2025-02-07,Carrefour,23.55,Mercado,Não,2025-02,3486.000000,Não
1,2025-02-08,TPG,45.00,Extra,Não,2025-02,3441.000000,Não
2,2025-02-08,CERN,10.90,Alimentação,Não,2025-02,3430.100000,Não
3,2025-02-08,Carrefour,8.41,Mercado,Não,2025-02,3421.690000,Não
4,2025-02-08,Hotel,0.67,Extra,Não,2025-02,3421.020000,Não
...,...,...,...,...,...,...,...,...
940,2026-03-16,SOCAR,3.95,Extra,Não,2026-03,60.020716,Sim
941,2026-03-17,Denner,7.70,Mercado,Não,2026-03,52.320716,Sim
942,2026-03-17,CERN,7.50,Alimentação,Não,2026-03,44.820716,Sim
943,2026-03-17,CERN,4.50,Alimentação,Não,2026-03,40.320716,Sim
944,2026-03-17,Wise Gastos,63.25,Wise Gastos,Não,2026-03,-22.929284,Sim

In [29]:
# ex =  df[(df['Pagamento?'] == 'Não') & (df['Categoria'] != 'Wise Save')].groupby('Mês Pagamento')['Valor'].sum().reset_index()

# ex['Mês Pagamento'] = ex['Mês Pagamento'].dt.to_timestamp().dt.strftime('%m/%y')

df['Ano Pagamento'] = df['Mês Pagamento'].dt.to_timestamp().dt.year


ano_atual = pd.Timestamp.now().year


df['Ano Pagamento Atual?'] = np.where(df['Ano Pagamento'] == ano_atual, 'Sim', 'Não')

df

,Data,Local,Valor,Categoria,Pagamento?,Mês Pagamento,Saldo,Mês Pagamento Atual?,Ano Pagamento,Ano Pagamento Atual?
0,2025-02-07,Carrefour,23.55,Mercado,Não,2025-02,3486.000000,Não,2025,Não
1,2025-02-08,TPG,45.00,Extra,Não,2025-02,3441.000000,Não,2025,Não
2,2025-02-08,CERN,10.90,Alimentação,Não,2025-02,3430.100000,Não,2025,Não
3,2025-02-08,Carrefour,8.41,Mercado,Não,2025-02,3421.690000,Não,2025,Não
4,2025-02-08,Hotel,0.67,Extra,Não,2025-02,3421.020000,Não,2025,Não
...,...,...,...,...,...,...,...,...,...,...
940,2026-03-16,SOCAR,3.95,Extra,Não,2026-03,60.020716,Sim,2026,Sim
941,2026-03-17,Denner,7.70,Mercado,Não,2026-03,52.320716,Sim,2026,Sim
942,2026-03-17,CERN,7.50,Alimentação,Não,2026-03,44.820716,Sim,2026,Sim
943,2026-03-17,CERN,4.50,Alimentação,Não,2026-03,40.320716,Sim,2026,Sim
944,2026-03-17,Wise Gastos,63.25,Wise Gastos,Não,2026-03,-22.929284,Sim,2026,Sim