In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect('../db/finance_control.db')
cursor = conn.cursor()

df = pd.read_sql_query("SELECT * from gastos", conn)

df.tail(10)

                    Data         Local     Valor
138  2026-03-12 00:00:00          CERN  11.95000
139  2026-03-12 00:00:00         SOCAR   2.95000
140  2026-03-12 00:00:00          Coop  14.30000
141  2026-03-13 00:00:00          Coop   6.45000
142  2026-03-13 00:00:00          CERN   1.70000
143  2026-03-13 00:00:00     OBrasseur  39.11722
144  2026-03-13 00:00:00    Boccadasse   9.00000
145  2026-03-13 00:00:00     McDonalds   5.00000
146  2026-03-15 00:00:00   Crozet Snow  39.50000
147  2026-03-15 00:00:00  Pretty Patty  23.00000

In [5]:
cursor.execute(
    """
    DELETE FROM gastos 
    WHERE Data = '2026-03-15 00:00:00'
    AND Local = 'Pretty Patty' 
    AND Valor = '23.00000'
    """
)
conn.commit()

In [6]:
df = pd.read_sql_query("SELECT * from gastos", conn)

df.tail(10)

                    Data       Local     Valor
136  2026-03-11 00:00:00      Luigia  31.00000
137  2026-03-11 00:00:00        Coop   5.20000
138  2026-03-12 00:00:00        CERN  11.95000
139  2026-03-12 00:00:00       SOCAR   2.95000
140  2026-03-12 00:00:00        Coop  14.30000
141  2026-03-13 00:00:00        Coop   6.45000
142  2026-03-13 00:00:00        CERN   1.70000
143  2026-03-13 00:00:00   OBrasseur  39.11722
144  2026-03-13 00:00:00  Boccadasse   9.00000
145  2026-03-13 00:00:00   McDonalds   5.00000